### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tanishkhandelwal**

### CODE REVIEW

**Comment by MarshallOfSound** [comment]
@Vitallium This is more hacktoberfest spam, can you tag it as "invalid" 😄

**Comment by Vitallium** [comment]
@MarshallOfSound we don't have such tag. Can I tag it as "declined"?

**Comment by MarshallOfSound** [comment]
I believe Digital Ocean only disregard PR's tagged as "invalid".  It's what the atom and electron teams have been tagging these PR's with.  Maybe add the "invalid" tag temporarily, hopefully there won't be too many of these coming your way 😆 

https://twitter.com/digitalocean/status/783763569812832256

**Comment by Vitallium** [comment]
@MarshallOfSound ah, ok! Not a problem. Tagged!

**Comment by MarshallOfSound** [comment]
Cutting down the hacktoberfest spam one PR at a time 😆 Thanks 👍

**Pull request closed without merging**
