### PR TITLE
Encode all the URLs

### PR DESCRIPTION
**Pull request by zackw**
Proposed fixes for #12216 and #11035.

### CODE REVIEW

**Comment by adon-at-work** [comment]
+1

**Comment by Vitallium** [comment]
@zackw could you please rebase this PR? I think we can land it to the master.

**Comment by zackw** [comment]
I still can't test it reliably (which is why I am overhauling the test
suite).  But I'll see what I can do.  Might be a couple days.

**Comment by zackw** [comment]
@Vitallium I've rebased it, but I don't think it's safe to merge as is.  Actually I could use your help on one aspect.  Please look at bug #11035 and see if you can figure out whether the underlying Webkit bug has been fixed.

**Comment by zackw** [comment]
**CAUTION:** This has been rebased on top of my `better-test-harness` branch.  I think that branch is ready to be merged, but don't merge this one unless you agree!

**Comment by zackw** [comment]
OK! Now that `better-test-harness` has been merged, it is possible to write reliable tests for this stuff (which I did a long time ago) and so I would like to propose this branch for merging as well.

**Pull request merged**
