### PR TITLE
added possibility to use proxy for localhost

### PR DESCRIPTION
**Pull request by lordldx**
Hi,

I added a config parameter  to indicate that the proxy should also be used for localhost.
Please consider merging.

Thank you.
Regards,
Lorenzo

### CODE REVIEW

**Comment by Aldaviva** [comment]
+1

**Comment by justinklemm** [comment]
+1

I'd love to see this, or something like it, merged. Being able to run local traffic through a proxy is an important feature.

**Comment by Aldaviva** [comment]
To clarify my use case, this would let people run PhantomJS traffic through a debugging proxy (Fiddler, Charles) on its way to a local web server under test, making it easy to see network traces.

**Comment by lordldx** [comment]
This is also one of the reasons i did this. 
Another is to be able to modify the url during automated integration tests


Verzonden vanaf Samsung Mobile.

<div>-------- Oorspronkelijk bericht --------</div><div>Van: Ben Hutchison <notifications@github.com> </div><div>Datum:16-01-2015  06:06  (GMT+01:00) </div><div>Aan: ariya/phantomjs <phantomjs@noreply.github.com> </div><div>Cc: Lorenzo Dieryckx <lorenzo.dieryckx@gmail.com> </div><div>Onderwerp: Re: [phantomjs] added possibility to use proxy for localhost (#12703) </div><div>
</div>To clarify my use case, this would let people run PhantomJS traffic through a debugging proxy (Fiddler, Charles) on its way to a local web server under test, making it easy to see network traces.

**Comment by romanlehnert** [comment]
+1

**Comment by lkwg82** [comment]
+1

**Comment by lkwg82** [comment]
:star: it can be workaround with calling `127.0.0.1.xip.io` as the target address, when the proxy is at the same address as the server. See http://xip.io/

**Comment by jecuendet** [comment]
+1

**Comment by zackw** [comment]
@lordldx Thank you for the contribution, and we're sorry it has taken so long for us to react.

Your pull request no longer merges cleanly, can you please rebase it on the latest trunk?  Also, please consider writing some test cases for the automatic test suite.  (If this looks like it's going to require major surgery on the test suite, don't worry about it.)

**Comment by lordldx** [comment]
@zackw 
Hey, I rebased the pull request. Should merge now.
Wasn't able to add a test, I don't have qt on my laptop anymore, sorry.
Hope it still compiles though 🙈

**Comment by dg-ratiodata** [comment]
@zackw Would you mind to review this again? I'm in the need to use phantomjs on localhost proxies. Thanks a lot.

**Comment by zackw** [comment]
I won't have time to look at this till March but I will try to remember to do it then.

**Comment by dg-ratiodata** [comment]
Great. Thanks. Just to give you an idea for what it's worth to have it:

Some time ago I started to build an extension for `rspec` - ruby testing framework - to test HTTP proxies infrastructures using CI. Using `capybara` + `poltergeist` I would be able to send out requests to the proxy servers while being able to navigate the webistes site (fetched via proxy) and check the results.

Unfortunately to build that software I need to run "local" proxies as part of the test suite. Using localhost for this makes the test suite work across most UNIX/Linux OS.

So, I really like to see this merged. Thanks a lot in advance.

**Pull request merged**
