### PR TITLE
added response body to response object in onResourceReceived event

### PR DESCRIPTION
**Pull request by dparshin**
added response body to response object in onResourceReceived event

https://github.com/ariya/phantomjs/issues/10158

### CODE REVIEW

**Comment by Vitallium** [comment]
This is really risky to implement this as a proxy between PhantomJS and Webkit. I remember we had a lot of issues with similar implementation.

**Comment by dparshin** [comment]
@Vitallium @ariya we've been using this patch for couple of years, issuing about 100k of requests daily. I'm pretty sure its not that risky, if you could point me to the issues you have encountered with this approach I'd gladly verify them and make fixes if necessary.

**Comment by Vitallium** [comment]
@dparshin in this case, I think we can merge it. 
/cc @ariya

**Comment by Vitallium** [comment]
Ok, I'm going to merge this! I played with it some time. Looks good and stable. If something will not work, blame it on me.
/cc @ariya  @dparshin

**Comment by dparshin** [comment]
@Vitallium, done

**Comment by Vitallium** [comment]
@dparshin landed! Thank you! You did awesome job!

**Comment by Vitallium** [comment]
Actually, wait. I can't merge it normally :X

**Comment by dparshin** [comment]
@Vitallium, is there anything wrong with it?

**Comment by Vitallium** [comment]
@dparshin no, I just need to merge it correctly

**Comment by Vitallium** [comment]
Phew. Now it's landed! Thanks!

**Comment by dparshin** [comment]
@Vitallium, great!Thanks.

**Comment by kriegaex** [comment]
Sorry for the stupid question: The PR was closed, but was it also merged into master or another branch? I cannot find the changes when browsing the repo.

**Comment by Vitallium** [comment]
@kriegaex yes, it was merged into master. But this PR caused weird errors for sync AJAX requests, and we reverted it. We landed a fix for sync AJAX requests some time ago. I think we can bring this feature back into the master branch.

**Comment by erikdubbelboer** [comment]
@Vitallium any ETA? Do you plan to use the same type of proxy class or will that not work anymore because of the AJAX issue?

**Comment by Vitallium** [comment]
@erikdubbelboer I think we can just pull the original code back. I'll try to land it this weekend.

**Comment by dpanic** [comment]
What is the situation with response.body in onResourceReceived on 2.1.1?

**Comment by yeyu456** [comment]
Same question.Is it done yet? I need that feature.Anything i can do right now? like using some old version.

**Comment by dominiceales** [comment]
I have some phantom scripts dependent on this functionality (written when it was working with an earlier version of 2.1.1)....and I really needed the functionality back so I have temporarily built using the commit bced581501344d80ece3f61005661e407d4b1148 - it works for my use case. (I hope this helps someone else, and that this functionality is back in an official version soon!)

**Comment by redzedi** [comment]
Using this [commit](https://github.com/ariya/phantomjs/commit/bced581501344d80ece3f61005661e407d4b1148)  causes Phantomjs to crash when navigating out of a page that has a window.onbeforeunload function that fires a async ajax POST request . Please refer to the html below :- 

```
<!DOCTYPE html>
<html>
<head>
    <script type="text/javascript">
    function testCallbackComplete(){
    	console.log("Done onbeforeunload !!");
    }
    	window.onbeforeunload = function(){
    		var xmlRequest = new XMLHttpRequest();
    		xmlRequest.onreadystatechange = testCallbackComplete;
    		xmlRequest.open("POST", encodeURI("http://localhost:5000/testEcho"), true);
       xmlRequest.setRequestHeader("Content-Type", "application/json");
        xmlRequest.send("{\"test\":true}");
        return;
    } 
    	
    </script>
	<title>testing On Before Unload</title>
</head>
<body>
   <p>
   	<a href="index.html" id="goToIndex">Go to Index</a>
   </p>

</body>
</html>
```

**Pull request closed without merging**
