### PR TITLE
Added little information about the webpage instance

### PR DESCRIPTION
**Pull request by venam**
I noticed there wasn't really any info in the documentation about the webpage instance so I tried adding some.
It's not perfect but it's still better than having to dig through the code.

### CODE REVIEW

**Comment by Vitallium** [comment]
Landed. Thank you!

**Comment by venam** [comment]
I think there's a problem with the highlight. On the website it doesn't show the code as javascript but in the preview it works fine. It might be because the renderer you are using needs a space before the triple backticks.

**Comment by Vitallium** [comment]
@venam and the link on the bottom is not clickable

**Comment by venam** [comment]
I'll fix those and redo the pull request.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://interimeks.com/servant.php?1>

 

klaus@hebsgaard.dk

**Pull request merged**
