### PR TITLE
Change 'hundreds' to 'thousands' in README.md

### PR DESCRIPTION
**Pull request by jillesme**
I've been using PhantomJS for a long time now at multiple companies. Every rather experienced JavaScript developer I know uses or has used PhantomJS. Hence I think it should at least be 'thousands of developers'

### CODE REVIEW

**Comment by Kuzirashi** [comment]
I agree. This repo has 15,355 stars.

**Comment by fvanwijk** [comment]
The term 'dozens' also needs some inflation by now :)

**Comment by zackw** [comment]
Given that neither buzz.html nor users.html appears to have been updated in Quite Some Time and are no longer prominently featured on the main website, I have elected instead to remove the sentence.

**Comment by ariya** [comment]
:+1: with the removal. This was only relevant long time ago when PhantomJS was relatively unknown.

**Pull request closed without merging**
