### PR TITLE
Reimplement Paxa's diskCachPath

### PR DESCRIPTION
**Pull request by malhotrar**
We had a need and find the following extrememly useful: https://github.com/ariya/phantomjs/pull/11237

I've copied the relevant code to make it compatible with 2.0; Even if you do not accept, could you accelerate the other pull request?

### CODE REVIEW

**Comment by ariya** [comment]
Thanks for taking the time to look at this! I'll give it a try shortly.

**Comment by davidkearns** [comment]
I'd love to see this merged in and included in the next release. I also have a great need for this.

**Comment by malhotrar** [comment]
Ariya - have you had a chance to try this out? My colleagues and I are ready to use this, but do not want to deviate from the current release.

**Comment by madelson** [comment]
:+1:  any timeline for when this will be merged in? Without this, we can't use disk caching at all, which really hurts performance.

**Comment by malhotrar** [comment]
Any update?

**Comment by davidkearns** [comment]
@ariya or @Vitallium any update on this?

**Comment by Vitallium** [comment]
@davidkearns I'll take a look into this asap.

**Comment by zackw** [comment]
Not relevant anymore. See c9e30eb

**Pull request closed without merging**
