### PR TITLE
Add end-of-life notice to README.md

### PR DESCRIPTION
**Pull request by csvan**
Add notice that the project has been discontinued (since a lot of people are still filing bugs)

### CODE REVIEW

**Review by hugovk — APPROVED** [review]

**Comment by RWOverdijk** [comment]
👍 ...

**Comment by pixiuPL** [comment]
I would put statements like these on hold. Closing this PR

**Comment by hugovk** [comment]
@pixiuPL Is the project still active? https://github.com/ariya/phantomjs/issues/15105 suggests otherwise. Thank you!

**Comment by csvan** [comment]
@pixiuPL your call, but the overall impression judging by the issue tracker seems to be that the project is still active, despite clear statements to the contrary.

**Pull request closed without merging**
