### PR TITLE
Upgrade Qt to 5.4.1

### PR DESCRIPTION
**Pull request by vitallium**
Check list, i.e. can we build PhantomJS on:
- [x] OS X
- [x] Linux
- [x] Windows

Other:
- [ ] Upgrade to 5.4.2

Related issue: #13215

### CODE REVIEW

**Comment by level420** [comment]
@Vitallium the title should be Upgrade Qt 5.4.1... there is a swap in the version number

**Comment by Vitallium** [comment]
@level420 whoops... Thanks!

**Comment by Vitallium** [comment]
Fixed build on Windows.

**Comment by Vitallium** [comment]
Ready to merge.

/cc @ariya

**Comment by iradul** [comment]
:+1:

**Comment by Vitallium** [comment]
Updating this pull request to 5.4.2...

**Comment by jefleponot** [comment]
Very good job @Vitallium 
it works on Centos 6.5

**Comment by mtparet** [comment]
:+1:

**Comment by LinusU** [comment]
@ariya Any change of merging this?

**Comment by ariya** [comment]
LGTM. @Vitallium Feel free to merge this (keep the history linear please). Thanks!

**Comment by iradul** [comment]
@Vitallium you might want to check debugging version. I'm getting crashes with a simplest script:
```javascript
var page = require('webpage').create();
page.open('http://google.com');
```
There are many *invalid heap* errors thrown on this line ```\src\qt\qtwebkit\Source\WebCore\platform\Timer.cpp#314```
Release version works great thought.

**Comment by Vitallium** [comment]
FYI: with the upgrade to Qt 4.5.2 we'll don't need manipulations with libicu anymore. They fixed suffixes for debug versions.

**Comment by Vitallium** [comment]
@iradul I'll check it. But AFAIK everything should be normal with this upgrade.

**Comment by ariya** [comment]
@Vitallium :+1: Thanks so much for this effort!

**Comment by iradul** [comment]
@Vitallium have you got time to check debugging version ?
The cause of *invalid heap* error is introduced with [this qt commit](https://github.com/qtproject/qtbase/commit/3006bd2d44298babd1339c3fc3a67ad0696bcefc#diff-89c3364c5d79ab8ca3e6573c8b51c71e).
After those ```t1``` and ```t2``` were initialized to negative numbers function [```QElapsedTimer::nsecsElapsed()```](https://github.com/ariya/phantomjs/blob/master/src/qt/qtbase/src/corelib/tools/qelapsedtimer_win.cpp#L160) got messed up so later on as soon as it's being used in pipeline (by ```QWebFrame``` constructor) timer event is fired too early and processing of it finally leads to *invalid heap* error. So for me this fixes debugging version, [here](https://github.com/ariya/phantomjs/blob/master/src/qt/qtbase/src/corelib/tools/qelapsedtimer.h#L53) I'm using:
```
Q_DECL_CONSTEXPR QElapsedTimer()
        : t1(Q_INT64_C(0)),
          t2(Q_INT64_C(0))
    {
    }
```
[](#13339)

**Comment by Vitallium** [comment]
@iradul yes, I checked it. But it looks fine to me. I tried it on all 3 platforms.

**Comment by sodabrew** [comment]
This is fantastic! Is there any community work that would help move towards a next release, e.g. specific things to test, platforms to build on, etc.?

**Comment by sodabrew** [comment]
I just did a local build of master, and it works great. Is there anything holding up calling this a 2.1.0 release? Is there any community work or testing that would help towards this?

**Comment by ariya** [comment]
@sodabrew That's the plan (to roll out 2.1), we're just quite busy with many other stuff. But, stay tuned!

**Comment by sodabrew** [comment]
Is there anything the community can help with at this time?

**Pull request merged**
