### PR TITLE
fix javascript code with jshint/eslint/...

### PR DESCRIPTION
**Pull request by jefleponot**
refs  #13313 
in child_process.js :  some Functions was used before it was defined

### CODE REVIEW

**Comment by LinusU** [comment]
Why double quotes? [Most people in the javascript community](http://sideeffect.kr/popularconvention/#javascript) prefers single quotes.

Also, why not just follow [feross/standard](https://github.com/feross/standard) which is becoming the most popular coding standard.

**Comment by JamesMGreene** [comment]
> Also, why not just follow feross/standard which is becoming the most popular coding standard.

Interesting claim, considering its repo has fewer stars than JSHint, ESLint, JSCS, JSLint, etc....

**Comment by LinusU** [comment]
JSHint, ESLint, JSCS and JSLint are **linting engines** while feross/standard is a **coding style**. If you want to compare stars you'll have to look at other repositories. Internally standard uses eslint.

The reason I said it's becoming the most popular is that I've seen it being used in a lot of new modules...

**Comment by jefleponot** [comment]
you're all right. However the current codes are full of syntax errors (missing semicolon, rough conditions ...)

it could be nice to patch that.

**Comment by Vitallium** [comment]
I don't think this is a really critical issue. So, I leave this to others.

**Comment by zackw** [comment]
I'm for lint-cleanliness in general, but the patch as-is is not practical to review, and by now it's bitrotted to the point where it will be easier to start over, anyway.

What we're going to need you to do is submit a whole series of patches (one pull request, but many commits), each commit correcting *one type of lint complaint* across the whole codebase.  This is much, much easier to review than a patch that does everything at once.

I'm closing this PR because we can't merge it as is.  You may either reopen it with updated patches or file a new one.

**Pull request closed without merging**
