### PR TITLE
Handle empty stack processing onError

### PR DESCRIPTION
**Pull request by mepard**
#14110

### CODE REVIEW

**Comment by ariya** [comment]
@mepard The safeguarding looks good. Is it possible to add a test for this?

**Comment by mepard** [comment]
I tried to figure out what was causing it and craft a test to reproduce it, but nothing I tried triggered the problem. I suspect it might be due to New Relic's problem reporting mechanism, but I'm not sure.

**Comment by Vitallium** [comment]
Looks fine. But I already covered it here https://github.com/Vitallium/phantomjs/commit/5bf5bf910b302bc9c44a80d200b8024e61fff687

**Comment by astefanutti** [comment]
Since the upgrade to Qt 5.6, it looks like QtWebkit raises an error whenever a page contains an unknown `viewport` content key. Which leads to having an empty stack as it is irrelevant. This occurs with the `minimal-ui` value which is not recognised though largely widespread so that increases a lot the occurence of that error (like every reveal.js presentation has it).

Even if the proposed fix isn't covering all the possible use cases, it'd be valuable to merge it and cover at least that use case.

**Comment by astefanutti** [comment]
@mepard you can use the following page as test case:
```
<html>
<head>
<meta name="viewport" content="width=device-width,minimum-ui">
<title>foo</title>
</head>
<body>
Test
</body>
</html>
```

**Pull request merged**
