### PR TITLE
Deactivate UserGestureIndicator

### PR DESCRIPTION
**Pull request by Drahakar**
fixes issue #12506 ariya#12506

Since phantomJS is a headless browser, evaluating if the gesture comes
from a user is pointless. The UserGestureIndicator is now a dummy class
that always returns true.

### CODE REVIEW

**Comment by Drahakar** [comment]
This is also making a bunch of other tests passes.

The run-tests.js goes from 34 failures to 18 failures with this PR.

**Comment by ariya** [comment]
This touches Qt. Please see if this should be upstreamed first.

**Comment by Drahakar** [comment]
@ariya Are you refering to the upstream specified in this PR : https://github.com/ariya/phantomjs/issues/12426 ?

**Comment by ariya** [comment]
Upstream Qt = https://bugreports.qt.io/browse/QTBUG. See e.g. #12760.

**Comment by Vitallium** [comment]
Hi! Could you please file your pull request against this repo https://github.com/Vitallium/qtwebkit ?
Also, this is kind of a hack. I would like to disable gestures via features.

**Pull request closed without merging**
