### PR TITLE
Better test harness (#13478)

### PR DESCRIPTION
**Pull request by zackw**
This pull request contains the changes proposed in bug #13478.  It is now ready to be reviewed.

### CODE REVIEW

**Comment by Vitallium** [comment]
Whoa... That's a lot of changes.

**Comment by zackw** [comment]
The diffs look bigger than they really are, because they move a whole lot of stuff around and delete several very large files.  But yes, it's a big twinkie (and has occupied basically all of my work time for the past two weeks).  

https://github.com/zackw/phantomjs/blob/better-test-harness/test/writing-tests.md is documentation for writing tests the new way.  That should be a good place to start.  The changes to `run-tests.py` and the code in `testharness.js` are probably worth looking at carefully; everything else is just "rewrite existing tests the new way".

**Comment by Vitallium** [comment]
FYI, I applied this PR to the master and run `run-tests.py`. Here is the result:
```
344.850s elapsed
  102 passed
   68 failed
    7 failed as expected
   74 had errors
    5 skipped
```
You can find the full log here: https://gist.github.com/Vitallium/53526d5059a81d1801e0
Also, I applied a small fix to disable color output on Windows. Windows doesn't have `tput`.

**Comment by zackw** [comment]
Ugh.  I see none of that on OSX, and I don't have access to a Windows development environment.  I may need you to debug that at least somewhat -- I think, for instance, that the LEAK: messages are coming from some debugging mode of Visual Studio, so there's no way I can pin them down.

The fundamental problem here is, I think, that `run-tests.py` now considers it a failure if the phantomjs executable prints *anything* to standard error (unless specifically instructed otherwise).  We may need to add some sort of filter system.

If you repeat the test run with `run-tests.py -vvvv`, it'll print out a lot more detail and that will make debugging easier.  (You will probably want to redirect it to a file.)

**Comment by ariya** [comment]
Thanks a lot! This looks good to me. For those Windows issue, we may need to exclude/filter certain messages.

Also, this might be painful, but it would be nice to mention the issue for each commit for cross-reference purposes. I can do that once this is about to be merged.

**Comment by zackw** [comment]
> This might be painful, but it would be nice to mention the issue for each commit for cross-reference purposes. I can do that once this is about to be merged.

I noticed an error in the documentation, which is near the bottom of the stack, so I was going to have to rebase -i the entire thing anyway, so I have added a line to the bottom of each commit message mentioning the issue number.

Also I have verified that there are no problems on Linux as well as OSX.  Please note that in order to do that I had to stack it on top of the fix for #13518.

**Comment by zackw** [comment]
Any chance we could land this soon?  Any news on the Windows situation, @Vitallium ?

**Comment by Vitallium** [comment]
@zackw I'll take look into it today.

**Comment by Vitallium** [comment]
So, LGTM! We can land it to the `master`. And after I'll commit fixes for Windows.

/cc @ariya @JamesMGreene @zackw

**Comment by zackw** [comment]
Yay! I am rebasing the branch and will land it after testing.

**Comment by Vitallium** [comment]
Cool! Thanks!

**Pull request merged**
