### PR TITLE
New clean and shiny architecture

### PR DESCRIPTION
**Pull request by vitallium**
New clean and shiny architecture

This commit makes our architecture more simple and clean.
It introduces:
- PhantomPage - host page for the main execution context
- CustomPage moved to its own file (header + source)
- Config renamed to Settings
- QtWebKit dropped support for old compilers, so we can safely use precompiled headers - config.h
- decoupled page renderer. I moved page renderer to its own class to solve problems
with printing a web page to PDF. With this new class, we can use clipRect for PDF

This architecture is more stable and consumes less memory because
of correct QObject relations. All nested (dependent) object
will be deleted correctly.

### CODE REVIEW

**Comment by Vitallium** [comment]
Tests update:
```
  172 passed
   30 failed
   19 failed as expected
    1 had errors
    2 skipped
```

**Comment by Vitallium** [comment]
Tests update (Linux):

```
23.178s elapsed
  176 passed
   20 failed
    8 failed as expected
    7 had errors
    2 skipped
```

**Comment by jesg** [comment]
@Vitallium which version of qt did you use for this feature?

**Comment by GehDoc** [comment]
@Vitallium : Can you double-check your changes on  System::~System() ?
It seems that you have inverted the logic (previous code : tests for !null pointers. now : tests for null pointers).

**Comment by Vitallium** [comment]
@GehDoc 
image
I did it again...
https://github.com/ariya/phantomjs/commit/928d635349c2ef14b11c4715f2b70b94c78bc3f4

Thank you!

**Comment by Vitallium** [comment]
@jesg 5.9.1. Qt 5.8 has a critical bug fix for QtNetwork. Plus, I want to try new Qt light build for PJS. Just to clarify, minimum supported version is 5.7.1.

**Comment by pixiuPL** [comment]
@Vitallium sounds good to me :)

**Comment by pixiuPL** [comment]
This should be milestone based on this.
Will try and resolve conflicts and finally merge.

**Pull request merged**
