### PR TITLE
upload file bug

### PR DESCRIPTION
**Pull request by sureshvv**
Upload file does not work in 2.0 because of Qt change

### CODE REVIEW

**Comment by kowal** [comment]
+1 for this one. It solves file uploading issues for us. Thanks @sureshvv!

**Comment by sureshvv** [comment]
Does this support the multiple file upload feature?

**Comment by sureshvv** [comment]
See https://github.com/ariya/phantomjs/issues/12506

**Comment by Vitallium** [comment]
Not applicable anymore.

**Pull request closed without merging**
