### PR TITLE
Update the rpm specfile to phantomjs 2.0.0

### PR DESCRIPTION
**Pull request by fdintino**

### CODE REVIEW

**Comment by Vitallium** [comment]
@fdintino could you please update pull request to reflect recent changes?

**Comment by fdintino** [comment]
Absolutely. I'll get to this later today.

**Comment by fdintino** [comment]
I've rebased off of the latest master. I've also slightly tweaked mkrpm.sh so that it works with the more standard spec file.

**Comment by Vitallium** [comment]
Landed! Thanks!

**Pull request merged**
