### PR TITLE
Remove extra quote

### PR DESCRIPTION
**Pull request by ntzm**

### CODE REVIEW

**Comment by anatolinicolae** [comment]
There's like 2K issues, but priorities first.

**Comment by ntzm** [comment]
Feel free to fix them 😄

**Comment by anatolinicolae** [comment]
Nah, will probably stick with extra quotes and capitalization...

**Comment by ntzm** [comment]
I'm trying to contribute in a useful way. No need to be rude 😢

**Comment by brutalcrozt** [comment]
> I'm trying to contribute in a useful way. No need to be rude

No need to be sad world is a hard place, let's be strong :smile:

**Comment by Riari** [comment]
lol. This could have been merged in the time it took to comment about priorities instead 🙃

**Comment by rooor2011** [comment]
English

**Pull request merged**
