### PR TITLE
Applies qt patch from wkhtmltopdf project. Closes #10196

### LINKED ISSUE #10196: Suggestion: Include hyperlink action in PDF output for hyperlinks in webpage
_**[Guido...@gmail.com](http://code.google.com/u/107972423138417796022/) commented:**_
> PhantomJS v1.2.0
> 
> If you rasterie the URL http://www.nu.nl/buitenland/2590433/voedselhulp-wordt-in-mogadishu-gestolen-.html, it contains selectable text in PDF. Which is great!
> 
> But this news page contains a lot of link when opened in a normal browser.
> The PDF output shows no similar hyperlinks on the available text.
> 
> My suggestion: associate a hyperlink action where relevant.
> 
> This allows the PDF to more resemble the actual website.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #196](http://code.google.com/p/phantomjs/issues/detail?id=196).
:star2: &nbsp; **8** people had starred this issue at the time of migration.

### PR DESCRIPTION
**Pull request by nhodges**
Applies patch from: https://github.com/wkhtmltopdf/qt/commit/1613031d3d7fb75820f19f367fcdb96a43395e21

Closes #10196

### CODE REVIEW

**Comment by timmipetit** [comment]
Nice work! I haven't compiled and used this PR yet, but this looks like it adds the functionality to create hyperlinks in the PDF, but doesn't actually create the hyperlinks when converting from HTML to PDF yet?

To close #10196 it also needs to search for links and add them to the output, right? (as described here: https://github.com/ariya/phantomjs/issues/10196#issuecomment-73510368)

**Comment by nhodges** [comment]
Ah yes, you're right. I'm not as familiar with the phantomjs codebase as some others might be, so maybe someone wants to jump in to get this over the hump? It looks like the 3 modifications @timmipetit pointed out should go in src/webpage.cpp (I could be wrong, though)

**Comment by astefanutti** [comment]
I think that PR can be closed as it's superseded by https://github.com/ariya/phantomjs/pull/13250.

**Comment by Vitallium** [comment]
@ashkulz is it ok to include these changes? I think we already have a reference (copyright) to your project. If no, we can add it.

**Comment by astefanutti** [comment]
@Vitallium this PR does not fix #10196. it provides the foundation to support link creation in PDF output. #13250 is the peer-reviewed and complete version that has already been merged in `qtbase` since qtproject/qtbase@e9eeb68a656bd52c4a783dc4247c627c5363209a.

**Comment by Vitallium** [comment]
@astefanutti ok, great! Thanks! I thought it will be in 5.5, but it landed to v5.6.0-alpha1 Damn.
But anyway I'm going to merge your PR.

**Comment by Vitallium** [comment]
We're going to merge https://github.com/ariya/phantomjs/pull/13250 instead of this one.
Mentioned pull request already reviewed and merged to Qt.

Thanks!

**Pull request closed without merging**
