### PR TITLE
Font crash bug

### PR DESCRIPTION
**Pull request by yali25**
This fix is a modification in QT. It fixes a lot of SEGFAULT crashes with PhantomJS 2.0
e.g.
#13124
#13003

### CODE REVIEW

**Comment by MarkR42** [comment]
This fixes #13003 for me.

I've found many pages which reproduce it including http://eenadu.net/

**Comment by plamzi** [comment]
This fixes https://github.com/ariya/phantomjs/issues/13289 for me.

**Comment by Gvidco** [comment]
Fixes #13277

**Comment by xabufr** [comment]
It seems 79ad1985790d2bd86cc310be0a5ebb1066950182 solve this bug...
https://github.com/ariya/phantomjs/blame/master/src/qt/qtbase/src/platformsupport/fontdatabases/fontconfig/qfontconfigdatabase.cpp#L617

**Pull request closed without merging**
