### PR TITLE
Fix bodySize in onResourceReceived end, fix #10156

### LINKED ISSUE #10156: Get amount of transfered bytes
_**[marcon...@gmail.com](http://code.google.com/u/105745826760144045943/) commented:**_

> There is no way to reliably get the amount of transfered bytes for a request.
> 
> bodySize is not available for responses with stage==end and the content-length header is not very reliable, especially as it seems to be unset for requests with content-encoding &quot;gzip&quot;.
> 
> I guess the bodySize has to be summed up for each bunch of data received and made available in a respose with stage==end.

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #156](http://code.google.com/p/phantomjs/issues/detail?id=156).
:star2: &nbsp; **9** people had starred this issue at the time of migration.

### PR DESCRIPTION
**Pull request by erikdubbelboer**

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
If this gets merged #13195 can be closed.

**Comment by zackw** [comment]
I don't understand the core code changes well enough to review them, but, for the test case: please try to use the Python webserver for your test case, not the PJS-embedded webserver.  It can be extended with `.py` files in the `test/www` directory.  If you can't make it work we can discuss changing it.

(The embedded webserver has architectural problems that can cause deadlocks when used like you're doing.)

**Comment by erikdubbelboer** [comment]
I updated the pull request so the test uses the python webserver.

**Comment by tiwilliam** [comment]
I can confirm that this PR fixes my issue in phantomas when running trying calculate size of chunked content. Would love to see this merged.

macbre/phantomas#614

**Comment by abozhilov** [comment]
@erikdubbelboer any chances for new PR compatible with 2.1.1? https://github.com/ariya/phantomjs/issues/13908 breaks the current patch, as you know.

**Pull request merged**
