### PR TITLE
add simple feature: set Text to renders

### PR DESCRIPTION
**Pull request by jefleponot**
#12915 Pictures aren't comment : no date no text
so it's difficult to parse pictures

### CODE REVIEW

**Comment by Vitallium** [comment]
I think it's out of the scope of PhantomJS.

/cc @ariya @JamesMGreene @zackw

**Comment by jefleponot** [comment]
Hi Vitallium,

It's not true.

On the contrary, when you take a screenshot, it is important to have a comment . This comment could explain in which conditions the picture has been shotted : 
- error (comment join this information for post analyse)
- comparison (ressembleJS / PhantomCss ...)
- origin ( scriptname which have created it)
- date
...

Renders are unusable without comments. 
This features add only one line more, please ............please let it merges.


Jef

/cc @Vitallium @ariya @JamesMGreene @zackw

**Comment by jmiller76** [comment]
I use an external library to add annotations to PDFs, would something external be a functional alternative if the PR doesn't work?

**Comment by Vitallium** [comment]
Out of scope of the project.

**Pull request closed without merging**
