### PR TITLE
Upgrade Ghostdriver to support PhantomJS 2

### PR DESCRIPTION
**Pull request by vitallium**
WIP

### CODE REVIEW

**Comment by zackw** [comment]
This should really be in 2.1 if possible; what's the status?

**Comment by Vitallium** [comment]
It's hard to say. @detro is still looking for a maintainer for Ghostdriver.

**Comment by zackw** [comment]
Hmm, is what you have here enough of an improvement that we should go ahead and land it?

**Comment by PatrickHuetter** [comment]
I also think this should be in the next version. There are many ghostdriver user out there. What has to be done to make both compatible?

**Comment by jesg** [comment]
@zackw i'm working on updating the webdriver atoms in ghostdriver in pull request detro/ghostdriver#475.

@PatrickHuetter i have documented the test failures on two gists [1](https://gist.github.com/jesg/1f58af7236462841448f4a4ff5036aa7) and [2](https://gist.github.com/jesg/15cf2d2ac49bae362128f9b30f52c32e).

**Comment by Vitallium** [comment]
@jesg Whee! Awesome! Thank you!

**Comment by jesg** [comment]
i have pushed the patch to jesg/phantomjs@3ae4c36c39586b9ccaa964aa539cee1fd955d7aa.  these changes have not been merged into detro/ghostdriver.

should the ghostdriver version be bumped to 1.3.0?

**Comment by zackw** [comment]
Incidentally, people who care about ghostdriver might be interested in my branch <https://github.com/zackw/phantomjs/tree/integrate-ghostdriver-tests>, in which I'm trying to get rid of the requirement for Java to run the ghostdriver tests.  It's going very slowly because I have a lot of other demands on my time right now, and also because the Python WebDriver library seems to be unmaintained and incomplete. :disappointed: Still, I think it's worth doing, and extra hands would speed it up.  (Note: this is a feature branch and it *will* get rebased from time to time.)

**Comment by jesg** [comment]
what in paticular is missing in the python webdriver library?  the library looks active to me [https://github.com/SeleniumHQ/selenium/tree/master/py](https://github.com/SeleniumHQ/selenium/tree/master/py).  @zackw is the goal to maintain ghostdiver in the phantomjs project or to have tests in python?

looks like you integrated the python webdriver tests from the selenium project https://github.com/zackw/phantomjs/tree/407f4715a496e3028347ca65c6c5b66a67fd80ac/test/lib/py/selenium.

**Comment by zackw** [comment]
@jesg I integrated the Python webdriver _library_ from the Selenium project.  The tests are still the same as they ever were.  If there are additional tests available from the Selenium project we might want to think about integrating those too but that's not on my slate at the moment.

The goal is to have all of the tests in Python and run all of them from run-tests.py; WebDriver tests are the only thing we use Java for, at the moment, and that's a big twinkie for very little benefit.

https://github.com/zackw/phantomjs/commit/1e052d0bce9cb0d6ac658611226fbe87c9c864dd shows one case where I had to work around something missing from the library.  There were others -- it's been long enough since i last did anything with this code that I don't remember what they were, but if you read through the remaining .java files in test/ghostdriver-test/java/src/test/java/ghostdriver/ you will find them pretty quickly.

**Comment by jesg** [comment]
i don't think phantomjs or ghostdriver has any test coverage around selenium grid.  it may be good to have some basic tests.  the grid [tests](https://github.com/SeleniumHQ/selenium/tree/master/java/server/test/org/openqa/grid/e2e/node) in the selenium project are in java.

i'll take a look at test/ghostdriver-test/java/src/test/java/ghostdriver/ when i get a chance in the next couple of days.  do we want to work from these tests or the slightly more up to date tests in the ghostdriver project?

**Comment by Vitallium** [comment]
Outdated

**Pull request closed without merging**
