### PR TITLE
Fix an issue with loading of user modules

### PR DESCRIPTION
**Pull request by alexey89777**
fix an issue with loading of user modules contains comment at last string (for example typescripts compilled code with map info)

### CODE REVIEW

**Comment by ariya** [comment]
This changeset is hard to understand. Please open an issue first detailing what the problem is. For details, refers to https://github.com/ariya/phantomjs/blob/master/CONTRIBUTING.md.

**Comment by JamesMGreene** [comment]
FYI, I pulled the useful change out of this and committed it as a4cb01b2011fe528919fe2bb47d6ef2448790ced.

**Comment by JamesMGreene** [comment]
Thanks, @alexey89777!

**Comment by JamesMGreene** [comment]
(Amended that commit message to include a reference to this issue #12868.)

**Pull request closed without merging**
