### PR TITLE
Sleep until HTTP thread is running

### PR DESCRIPTION
**Pull request by catharsis**
This patch works around/ameliorates around a bug in QT 4
(https://bugreports.qt.io/browse/QTBUG-29452) which triggers the
infamous "pure virtual method called" crash. In summary, the problem is
that threads that are supposed to handle HTTP requests are not
necessarily fully constructed when time comes to do the handling.

This patch is only applicable for phantomjs 1.9, since later releases
to my understanding will use QT 5, in which the bug has been properly
fixed.

This workaround does a very primitive usleep()-loop, continually
checking for thread->isRunning() to make sure that we actually are ready
to deal with the request.

NB. This is not a proper fix, since the race condition might in theory
still occur. However, after running this patch (with a sleep celiing of
0.1 seconds, as opposed to the full 1 second in this patch) internally
it has significantly reduced the occurence of the issue. It took me a
full day of re-building to trigger the error. Again, that was with the
0.1 seconds, this patch increases that number by a factor of 10.

It's worth noting that, unsuprisingly, the issue is easier to reproduce
with a system under heavy load, such as a build slave building a lot of
things in parallel.

Note also that the workaround suggested in the bug report to QT is not
feasible:
    ...
    manager->httpThread->start();
    manager->httpThread->wait(20); // add this line
    ...

Partially, because this workaround applied verbatim only affects
asynchronous requests but moreso because:

"[the QThread::wait() function] also returns true if the thread has not been started yet."

See http://qt-project.org/doc/qt-4.8/qthread.html#wait.

This fixes issues #12325, #11651, #12006, #11687, #12816, #11857,
 #12054, #11577, #11597, #12284

This probably/possibly (but can't verify because of missing stack
traces) fixes issues #11047, #11347, #12026, #12309, #10666, #11696, #12133, #10823,
 #10717, #12348

And probably others that I couldn't find or that have already been
closed.

Signed-off-by: Anton Lofgren alofgren@op5.com

### CODE REVIEW

**Comment by hequ** [comment]
I upgraded our CI server from ubuntu 12.04 to ubuntu 14.04.1 and after building this version of phantomjs, we got rid of the 'pure virtual method called' -error. Now we have more passing than failing CI builds. 

I upgraded the ubuntu because I got some linker error when trying to build with ubuntu 12.04. There was no problem building with ubuntu 14.04.1.

However now we sometimes get a "Error: NETWORK_ERR: XMLHttpRequest Exception 101" from jquery.js when ajax is happening. This is still a huge improvement over the phantomjs 1.9.8 version so thank you for your effort with this patch. :)

**Comment by Vitallium** [comment]
LGTM!

**Comment by Drahakar** [comment]
Might also fix https://github.com/ariya/phantomjs/issues/12892

**Comment by catharsis** [comment]
@Drahakar It might, but I wouldn't bet on it. The stack trace for that error is not very similar to the one fixed by this patch. My gut feeling is that that is another instance of the same type of bug. I haven't seen that bug in our CI system, so I don't really have enough data to look into it, even if I were so inclined.

**Comment by catharsis** [comment]
@ariya @Vitallium 
I'm going through a bunch of my outstanding PRs - is there anything blocking this from getting merged?

**Comment by Vitallium** [comment]
Thanks for the pull request! 
But we don't maintain 1.x version anymore.

We really appreciate your time!

**Pull request closed without merging**
