### PR TITLE
Fix Linux static build

### PR DESCRIPTION
**Pull request by vitallium**
This PR contains commits to fix static build on Linux (and OS X?)

**TODO:**
- [x] OpenSSL
- [x] libicu
- [x] _reserved_

### CODE REVIEW

**Comment by mickaelandrieu** [comment]
hi @Vitallium, do we have any hint to solve libicu issue ? I don't know C++ i can't help :/

**Comment by Vitallium** [comment]
Ready to merge!

/cc @ariya

**Comment by mickaelandrieu** [comment]
@Vitallium cool !

**Comment by ariya** [comment]
@Vitallium It still does not work for me. I built the binary on on CentOS 6.6, Running it on Ubuntu 12.04 (precise), with fontconfig, libicu-dev, and libicu48 installed gives the following:

```
ldd ./phantomjs 
	linux-vdso.so.1 =>  (0x00007fff5b5ff000)
	libicudata.so.42 => not found
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007f1a00bbf000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f1a00922000)
	libjpeg.so.62 => not found
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007f1a006fa000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f1a004e2000)
	libicui18n.so.42 => not found
	libicuuc.so.42 => not found
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f1a002dd000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f1a000d5000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f19ffeb8000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f19ffbb7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f19ff8bb000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f19ff6a5000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f19ff2e6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f1a00dfc000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007f19ff0bc000)
```

What's your `ldd` output when you run it across different distribution?

**Comment by ariya** [comment]
@Vitallium Ah, OK. I need to build a customized ICU library first, let me try that.

**Comment by Vitallium** [comment]
Not valid anymore.

**Pull request closed without merging**
