### PR TITLE
add ghostdriver command line option

### PR DESCRIPTION
**Pull request by jesg**
the user can override the default ghostdriver bundled in phantomjs with
the --webdriver-ghostdriver-path. --webdriver-ghostdriver-path must
point to the main.js in the ghostdriver project.

issue #14553 

the following examples demonstrate the new functionality.
```sh
$ ./bin/phantomjs --debug true --wd --webdriver-ghostdriver-path ../ghostdriver/src/main.js
....
2016-12-07T19:14:55 [DEBUG] Phantom - execute: Starting Remote WebDriver mode
2016-12-07T19:14:55 [DEBUG] WebPage - setupFrame ""
2016-12-07T19:14:55 [DEBUG] FileSystem - _open: ":/modules/fs.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:14:55 [DEBUG] FileSystem - _open: ":/modules/system.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:14:55 [DEBUG] FileSystem - _open: ":/modules/webpage.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:14:55 [DEBUG] FileSystem - _open: ":/modules/webserver.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:14:55 [DEBUG] FileSystem - _open: "/home/jesg/opensource/ghostdriver/src/hub_register.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:14:55 [DEBUG] FileSystem - _open: "/home/jesg/opensource/ghostdriver/src/logger.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:14:55 [DEBUG] FileSystem - _open: "/home/jesg/opensource/ghostdriver/src/third_party/console++.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:14:55 [DEBUG] FileSystem - _open: "/home/jesg/opensource/ghostdriver/src/config.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:14:55 [DEBUG] FileSystem - _open: "/home/jesg/opensource/ghostdriver/src/third_party/parseuri.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:14:55 [DEBUG] Phantom - injectJs: "session.js"
2016-12-07T19:14:55 [DEBUG] Phantom - injectJs: "inputs.js"
2016-12-07T19:14:55 [DEBUG] Phantom - injectJs: "request_handlers/request_handler.js"
2016-12-07T19:14:55 [DEBUG] Phantom - injectJs: "request_handlers/status_request_handler.js"
2016-12-07T19:14:55 [DEBUG] FileSystem - _open: "/home/jesg/opensource/ghostdriver/src/errors.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:14:55 [DEBUG] Phantom - injectJs: "request_handlers/shutdown_request_handler.js"
2016-12-07T19:14:55 [DEBUG] Phantom - injectJs: "request_handlers/session_manager_request_handler.js"
2016-12-07T19:14:55 [DEBUG] Phantom - injectJs: "request_handlers/session_request_handler.js"
2016-12-07T19:14:55 [DEBUG] Phantom - injectJs: "request_handlers/webelement_request_handler.js"
2016-12-07T19:14:55 [DEBUG] Phantom - injectJs: "request_handlers/router_request_handler.js"
2016-12-07T19:14:55 [DEBUG] Phantom - injectJs: "webelementlocator.js"
[INFO  - 2016-12-08T03:14:55.715Z] GhostDriver - Main - running on port 127.0.0.1:8910
```

and running packaged ghostdriver
```sh
$ ./bin/phantomjs --debug true --wd
...
2016-12-07T19:17:21 [DEBUG] Phantom - execute: Starting Remote WebDriver mode
2016-12-07T19:17:21 [DEBUG] WebPage - setupFrame ""
2016-12-07T19:17:21 [DEBUG] FileSystem - _open: ":/modules/fs.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:17:21 [DEBUG] FileSystem - _open: ":/modules/system.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:17:21 [DEBUG] FileSystem - _open: ":/modules/webpage.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:17:21 [DEBUG] FileSystem - _open: ":/modules/webserver.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:17:21 [DEBUG] FileSystem - _open: ":ghostdriver/./hub_register.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:17:21 [DEBUG] FileSystem - _open: ":ghostdriver/./logger.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:17:21 [DEBUG] FileSystem - _open: ":ghostdriver/./third_party/console++.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:17:21 [DEBUG] FileSystem - _open: ":ghostdriver/./config.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:17:21 [DEBUG] FileSystem - _open: ":ghostdriver/./third_party/parseuri.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: "session.js"
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: "inputs.js"
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: "request_handlers/request_handler.js"
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: "request_handlers/status_request_handler.js"
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
2016-12-07T19:17:21 [DEBUG] FileSystem - _open: ":ghostdriver/./errors.js" QMap(("mode", QVariant(QString, "r")))
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: "request_handlers/shutdown_request_handler.js"
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: "request_handlers/session_manager_request_handler.js"
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: "request_handlers/session_request_handler.js"
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: "request_handlers/webelement_request_handler.js"
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: "request_handlers/router_request_handler.js"
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: "webelementlocator.js"
2016-12-07T19:17:21 [DEBUG] Phantom - injectJs: prepending ":/ghostdriver/"
[INFO  - 2016-12-08T03:17:21.359Z] GhostDriver - Main - running on port 127.0.0.1:8910
```

i built and tested this on linux gcc 5.4.0, qt5.6.1, and annulen/webkit.

### CODE REVIEW

**Comment by Vitallium** [comment]
Nice! But how does it differ from existing property `phantomjs.ghostdriver.path` in Ghostdriver? Ref: https://github.com/detro/ghostdriver#what-extra-webdriver-capabilities-ghostdriver-offers

**Comment by jesg** [comment]
@Vitallium

> But how is it differs from the existing property `phantomjs.ghostdriver.path` in Ghostdriver?

the option i added works with every selenium client for phantomjs. `phantomjs.ghostdriver.path` is only implemented in the java client.  for reference `phantomjs.ghostdriver.path` is used in the [client]( https://github.com/detro/ghostdriver/blob/master/binding/java/src/main/java/org/openqa/selenium/phantomjs/PhantomJSDriverService.java#L519) not the driver.

it has more visibility by being in the command line options.

**Comment by Vitallium** [comment]
@jesg ah! I see! Thank you! LGTM :)

**Comment by pixiuPL** [comment]
@ariya @Vitallium Could any of you correct these conflicts?

**Comment by jesg** [comment]
@pixiuPL i have some time this week to take a look.  is there a way for me to build the binary locally?  hopefully something easy like docker so i don't have to figure out how to built qtwebkit and qt for this version of phantomjs.

**Comment by pixiuPL** [comment]
@jesg sure; just download zipped `master` branch, unpack it and follow [this](http://phantomjs.org/build.html) closely to build PJS locally.

**Comment by jesg** [comment]
@pixiuPL i thought `build.py` was deprecated.  i don't see `build.py` in the repository.  are you sure the build documentation is up to date?

**Comment by pixiuPL** [comment]
@jesg Dont know that..... 
/cc @ariya @Vitallium will you take care?

**Pull request closed without merging**
