### PR TITLE
Add linux build automation

### PR DESCRIPTION
**Pull request by mtparet**
### Description
- Add Dockerfile / circleci to build phantomjs
  This will permit to get a linux binary and verify the compilation is working.

We can download the binary for each build https://circleci.com/gh/ifeelgoods/phantomjs/3#artifacts.

### CODE REVIEW

**Comment by Vitallium** [comment]
I wonder if CircleCI can handle our build. I see that they offer `Build Minutes per Month 1,500`. I don't think this is enough for PhantomJS.

**Comment by mtparet** [comment]
Indeed this would lead to only 16 builds possible by month...

**Comment by Vitallium** [comment]
Can they be triggered manually? And can we do builds for all supported platforms?

**Comment by mtparet** [comment]
To build for windows, we need dedicated CI like http://www.appveyor.com/ for OS X, travis could still handle it. 
Here, the interesting thing is just the Dockerfile so anyone can build the image for linux.
I'm looking in travis if we could keep the binary available to download and build for Mac OS too.

**Comment by Vitallium** [comment]
For Windows we have a VM in Azure. But I really want to have a service that can handle all platforms.

**Comment by ariya** [comment]
@mtparet Do you mind bringing this discussion to [phantomjs-dev mailing-list](https://groups.google.com/forum/#!forum/phantomjs-dev). We've been looking for a proper CI system for PhantomJS and so far any off-the-shelf systems did not fulfill our requirements.

**Comment by zackw** [comment]
I'm also working on a Docker-based build but it doesn't quite work yet, see [zackw/phantomjs/docker](https://github.com/zackw/phantomjs/tree/docker).  I'm about to go out of town for Christmas and may not have time to do anything more with it till January.

**Comment by ariya** [comment]
@zackw @mtparet Let's continue the Docker-based build discussion on #13822.

**Comment by ariya** [comment]
@mtparet Never mind the mailing-list, let's continue the CI build system on #13828.

**Pull request closed without merging**
