### PR TITLE
Increase memory available on Windows

### PR DESCRIPTION
**Pull request by mepard**
Prevents Memory Exhausted problems in some cases. See #11390 et al.

### CODE REVIEW

**Comment by Vitallium** [comment]
Could you please it wrap it for x86 only? Will be useful in future. Thanks!

**Comment by mepard** [comment]
@Vitallium  I'm not sure what you're asking.

**Comment by Vitallium** [comment]
@mepard nvm. I thought that this option should be disabled for 64-bit. But according to [this](https://msdn.microsoft.com/en-us/library/wz223b1z.aspx), it's enabled by default.
Sorry for bothering you! I'll merge it in a few minutes.

**Comment by Vitallium** [comment]
Landed in https://github.com/ariya/phantomjs/commit/4f48c360c65046f111477b4a0ee168d4c3ca32a8
Thank you!

**Pull request closed without merging**
