### PR TITLE
Make print DPI configurable via "page.paperSize.dpi" (default is 72)

### PR DESCRIPTION
**Pull request by 1st1**
Hi all,

This PR makes it possible to configure print DPI. Default setting of 72 makes some SVG files look very blurry when printing to PDF.

Couple of screenshots of PDFs:
- http://imgur.com/MFxH1tP (300dpi)
- http://imgur.com/s7RhIc4 (72dpi)

### CODE REVIEW

**Comment by snkashis** [comment]
+1

**Comment by arathael** [comment]
+1

**Comment by jasonnathan** [comment]
+1

**Comment by adrian-ludwig** [comment]
+1

**Comment by kubosador** [comment]
+1

**Comment by thierryc** [comment]
+1

**Comment by theaspect** [comment]
What the problem merging this issue? @ariya

**Comment by westoque** [comment]
:+1:

**Comment by Vitallium** [comment]
Closing this. We're going to implement this in different way.

**Comment by garthk** [comment]
@Vitallium, what was the different way?

**Comment by Vitallium** [comment]
@garthk we implemented this options via page's settings (`page.settings.dpi`)

**Pull request closed without merging**
