### PR TITLE
Add support to render pdf to base64.

### PR DESCRIPTION
**Pull request by Connorhd**
Update the PDF generation code to use QPdfWriter which can output to a buffer and therefore be easily used to generate base64.

https://github.com/ariya/phantomjs/issues/11192
https://github.com/ariya/phantomjs/issues/12392

### CODE REVIEW

**Comment by Vitallium** [comment]
Could you please write a test for it?

**Comment by Connorhd** [comment]
Added base64 tests based on the existing tests for render

**Comment by Vitallium** [comment]
Thank you! Landed in https://github.com/ariya/phantomjs/commit/7d7e5f345b646ef18d23138781ae94197335b342

**Comment by howardroark** [comment]
Yes, thanks for this!

**Pull request closed without merging**
