### PR TITLE
Support dpi setting for pdf generation

### PR DESCRIPTION
**Pull request by martonw**
issue link: https://github.com/ariya/phantomjs/issues/13553

### CODE REVIEW

**Comment by jozefvaclavik** [comment]
Is there anything holding this to be merged into master? We are waiting for this feature.

**Comment by jonnolen** [comment]
:+1:

**Comment by zackw** [comment]
We're sorry for leaving this for so long.  Unfortunately, because your patch touches code in QtWebkit, the pull request needs to be split: submit the QtWebkit changes to [Vitallium/qtwebkit](https://github.com/Vitallium/qtwebkit), then resubmit the remainder here.  If there is any way you can possibly make your changes work without touching QtWebkit code, that's preferred.

We would also appreciate it if you could document this feature (submit another pull request for the gh-pages branch of this repo).

**Comment by martonw** [comment]
Hi @zackw - I will check if there is any chance this patch could work w/o code modification in the qtwebkit source.

**Comment by martonw** [comment]
I do not see any better way than modifying QT source – see details below for anyone who wants to understand it in depth. 

@zackw I suppose I should fork the Vitallium/qtwebkit and create a feature branch based on 'phantomjs' branch then pull request right? For the remainder - I assume the commit should go to a newer version, which branch should I use as a base (master head?)

Details for DPI and pdf rendering:
qtwebkit assumes there is a primary display attached to the PC which is used by the QT app. When you are about to print a webpage, it tries to scale it the best possible way for printing. The reason why it do so is that monitor pixel density is typically around 72-96 DPI, while a typical printer resolution is 300-1200 DPI - so without any scaling the printed versions would look really small and impossible to read. So qtwebkit sets a zoom factor = (printer's DPI / primary screen's DPI) and uses it to scale whatever you print. 
Now this is not so great for phantomjs - or any headless browser - where the primary screen's resolution does not matter at all (should be ignored) and we just want to bypass the above scaling - meaning that a 300px wide box printed with 300 DPI should be 1 inch wide. 
As you do not want to change the primary screen's properties and this is not really configurable for qtwebkit, the QWebFrame::print method shall be modified to set the zoom factor to 1 (means no scaling).

**Comment by Vitallium** [comment]
Already landed. But thank you for spending your time on this!

**Pull request closed without merging**
