### PR TITLE
Update 2000-01-03-screen-capture.md

### PR DESCRIPTION
**Pull request by DanAtkinson**
Actually 49 lines now, but who's counting? :)

### CODE REVIEW

**Comment by gillesdemey** [comment]
It would probably be better not to include the SLOCs in the README so we don't have to keep it up to date.

**Comment by Vitallium** [comment]
I agree. Better to remove it.

**Comment by DanAtkinson** [comment]
I've updated the pull to remove all SLOCs.

**Comment by Vitallium** [comment]
Landed! Thank you!

**Pull request merged**
