### PR TITLE
Replace NULL (or 0) with Q_NULLPTR

### PR DESCRIPTION
**Pull request by vitallium**
This:

* will make our code compiler-independent;
* will modernize our code with modern C++ standards.

This merge request also replaces several C style casts.

### CODE REVIEW

**Comment by ariya** [comment]
Looks @vitallium! Is that the CI error with coding style?

**Comment by vitallium** [comment]
> Looks 👍 @vitallium! Is that the CI error with coding style?

Yeah, in `src/encoding.cpp`:
```diff
diff --git a/src/encoding.cpp b/src/encoding.cpp
index e0e07d331..5bd9e21b8 100644
--- a/src/encoding.cpp
+++ b/src/encoding.cpp
@@ -50,10 +50,10 @@ Encoding::Encoding(const QString& encoding)
 Encoding::~Encoding()
 {
     if (m_codec) {
-      // TODO: Encoding class does not inherit QObject, so
-      // we have to delete m_codec member manually;
-      m_codec = Q_NULLPTR;
-    }    
+        // TODO: Encoding class does not inherit QObject, so
+        // we have to delete m_codec member manually;
+        m_codec = Q_NULLPTR;
+    }
 }
 
 QString Encoding::decode(const QByteArray& bytes) const
```

**Review by ariya — APPROVED** [review]

**Comment by ariya** [comment]
On a second thought, since likely we will only use C++11, isn't good to just stick with `nullptr`?

**Comment by vitallium** [comment]
> On a second thought, since likely we will only use C++11, isn't good to just stick with `nullptr`?

I would say should we use more Qt specific things or write common C++ code without bringing Qt-related stuff, i.e. if we can write code without Qt then we just do it? If the answer is yes, then we should replace `Q_NULLPTR` with `nullptr`.

**Pull request merged**
