### PR TITLE
Prevent test assertion

### PR DESCRIPTION
**Pull request by mepard**
Prevent assertion running test/module/webpage/subwindows.js. See #13882

### CODE REVIEW

**Comment by mepard** [comment]
I'll try this again without the extra merges and such.

**Comment by Vitallium** [comment]
FYI: You don't need to close the PR. Just update your branch and the pull request will be updated automatically. With this approach you don't need to open another pull request.

**Comment by mepard** [comment]
Thanks. What I wanted to do was get rid of the extra commits, which were just to keep up with ariya:master. I'm still learning rebase, etc.

**Comment by mepard** [comment]
Okay. Finally figured out how to remove unwanted commits.

**Comment by Vitallium** [comment]
Landed in master! Thank you!

**Pull request closed without merging**
