### PR TITLE
Don't change the URL of the main execution context on `phantom::exit`

### PR DESCRIPTION
**Pull request by vitallium**
We shouldn't change the URL of the main execution context. Because this will change security policy of our main frame which leads to the following message: `Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file://bla.js. Domains, protocols and ports must match.`

We can fix it by isolating main frame of PhantomJS execution context. We can destroy it separately.

This fixes: #12697 #12660

### CODE REVIEW

**Comment by alexserver** [comment]
so this PR was closed, but was this merged to master ? I'm still having the problem with version 1.9.16

**Comment by tedtate** [comment]
@alexserver I have the same issue. 1.9.16 is the version of the node wrapper for Phantom (https://github.com/Medium/phantomjs) which currently uses the last release of the 1.9 branch of Phantom. Unfortunately, the latest release (1.9.8) doesn't include this fix and it seems like there aren't any plans to release it.

If you use 1.9.11 of the node wrapper it should fix the issue.

**Comment by alexserver** [comment]
@tedtate Oh I understand, it is confusing to see this between the node wrapper and the phantomjs binary. thanks man.

**Comment by khebbie** [comment]
Hello!

 

You have a new message, please read <http://find-it-usa.com/boil.php?mx>

 

klaus@hebsgaard.dk

**Pull request closed without merging**
