### PR TITLE
update ghostdriver for phantomjs 2.5

### PR DESCRIPTION
**Pull request by jesg**
* fix page load for phantomjs 2.5.0
* add unhandledPromptBehavior w3c capability
* add blacklist/whitelist filters
* fix sending keys to content editable elements
* fix file upload for phantomjs 2.5.0
* fix action chains with elements in iframes
* replace calls to execute_script with atoms
* add --remoteHost (@madhavajay)
* add w3c defaults for add cookie
* fix multiple file upload
* add w3c timeout defaults
* fix custom phantomjs headers
* add support for switch to parent frame (Chui Tey)
* add support for right click (Artur Signell)
* add zoomFactor capability
* fix reset log buffer after each post request
* fix registration with selenium grid
* various bug fixes

Issue #14553

### CODE REVIEW

**Comment by jesg** [comment]
all the ghostdriver unit tests pass except for the tests that depend on relative urls.

results from the selenium test suite.  i ignored the window switching tests, the frame switching tests, and any test that worked with relative urls.
```
org.openqa.selenium.ClickTest#testShouldBeAbleToClickOnASpanThatWrapsToTheNextLine
org.openqa.selenium.ContentEditableTest#testShouldBeAbleToTypeIntoContentEditableElementWithExistingValue
org.openqa.selenium.ContentEditableTest#testNonPrintableCharactersShouldWorkWithContentEditableOrDesignModeSet
org.openqa.selenium.CorrectEventFiringTest#testNativelyClickOverlappingElements
org.openqa.selenium.CorrectEventFiringTest#testClickOverlappingElements
org.openqa.selenium.CorrectEventFiringTest#testClickAnElementThatDisappear
org.openqa.selenium.ElementFindingTest#testFindingASingleElementByEmptyTagNameShouldThrow
org.openqa.selenium.ElementFindingTest#testFindingASingleElementByEmptyClassNameShouldThrow
org.openqa.selenium.ElementFindingTest#testFindingMultipleElementsByEmptyNameShouldReturnEmptyList
org.openqa.selenium.ElementFindingTest#testFindingMultipleElementsByEmptyIdShouldReturnEmptyList
org.openqa.selenium.ElementFindingTest#testFindingASingleElementByEmptyNameShouldThrow
org.openqa.selenium.ElementFindingTest#testFindingASingleElementByEmptyIdShouldThrow
org.openqa.selenium.ElementFindingTest#testFindingASingleElementByEmptyCssSelectorShouldThrow
org.openqa.selenium.I18nTest#testShouldBeAbleToActivateIMEEngine
org.openqa.selenium.PageLoadingTest#testShouldTimeoutIfAPageTakesTooLongToRefresh
org.openqa.selenium.PositionAndSizeTest#testShouldGetCoordinatesInViewPortOfAnElementInAFrame
org.openqa.selenium.PositionAndSizeTest#testShouldGetCoordinatesInViewPortOfAnElementInANestedFrame
org.openqa.selenium.VisibilityTest#testShouldNotBeAbleToTypeToAnElementThatIsNotDisplayed
org.openqa.selenium.interactions.BasicMouseInterfaceTest#testMoveRelativeToBody
org.openqa.selenium.interactions.BasicMouseInterfaceTest#testMovingMouseBackAndForthPastViewPort
org.openqa.selenium.interactions.BasicMouseInterfaceTest#testMousePositionIsNotPreservedInActionsChain
org.openqa.selenium.interactions.BasicMouseInterfaceTest#testMovingIntoAnImageEnclosedInALink
org.openqa.selenium.interactions.CombinedInputActionsTest#testShiftClickingOnMultiSelectionList
org.openqa.selenium.interactions.CombinedInputActionsTest#testCombiningShiftAndClickResultsInANewWindow
```

**Comment by axe312ger** [comment]
Go people! U can do it! Can't wait to test flexbox with phanomjs ☺️

👍

**Comment by haroon-sheikh** [comment]
@jesg Where are we with this? Is someone reviewing this yet? Can we start testing it?

**Comment by jesg** [comment]
> Where are we with this?

it is complete.

> Is someone reviewing this yet?

it was reviewed downstream in ghostdriver.

> Can we start testing it?

yes, some of the functionality around relative urls in javascript and redirects are broken in the beta release of phantomjs 2.5.  after cloning [ghostdriver](https://github.com/detro/ghostdriver) you can run it with a [bash script](https://github.com/jesg/ghostdriver/blob/0c53cb61c0db98579dcb51665b7d6458f328aca8/bin/ghostdriver.sh) i wrote.  if you find an issue then you should create a ticket in the [ghostdriver issue](https://github.com/detro/ghostdriver/issues) tracker with a reproducable example.

**Comment by pg1671** [comment]
Great work! Looking forward to a new build containing the updated ghostdriver.

Is there an update on when it might be released?

**Comment by haroon-sheikh** [comment]
@Vitallium @ariya Can we please review/merge this and have updated version of the 2.5 binaries so we can continue testing the beta version.

**Comment by haroon-sheikh** [comment]
@jesg how do I build the binaries locally? I cannot seem to find the `build.py` that used to be there for 2.1.1.

**Comment by jesg** [comment]
@haroon-sheikh i'll try to push a branch to my phantomjs fork that backports ghostdriver 2.0.0 to phantomjs 2.1.1 sometime this weekend.

**Comment by jesg** [comment]
@haroon-sheikh see branch [backport-ghostdriver-2-0-to-phantomjs-2-1](https://github.com/jesg/phantomjs/tree/backport-ghostdriver-2-0-to-phantomjs-2-1) and https://github.com/jesg/phantomjs/tree/backport-ghostdriver-2-0-to-phantomjs-2-1/deploy for build instructions.

**Comment by haroon-sheikh** [comment]
You're a legend @jesg! 👍 
Are there instruction for building your 2.5 version branch?

**Comment by jesg** [comment]
> Are there instruction for building your 2.5 version branch?

i don't have any instructions on how to build 2.5.  it is a pain.

building 2.5 beta is probably not worth your time and effort.  it has a few bugs around major features.

**Comment by haroon-sheikh** [comment]
Thanks @jesg 

Maybe you can help me with this problem.. I have a page which executes the following code on page load:

```
<script>
  window.MY_VARIABLE = {
    video: {
      play: function(mediaID) {
        console.log('MY_VARIABLE play was called with', {videoMediaID});
      }
    }
  };
  </script>
```

but for some reason it doesn't like it when I'm running the test with 2.0 but does work with current 2.5 beta.. However, I cannot use 2.5 due to `fix page load for phantomjs 2.5.` issue. Is there a setup that I'm missing in 2.0 that's not running this script.

**Comment by jesg** [comment]
@haroon-sheikh 
you are using a ECMAScript 2015 feature [Shorthand property names](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer) which is not supported prior to 2.5 beta.

**Comment by haroon-sheikh** [comment]
@Vitallium thanks for merging this. Can we please have the updated binaries in bitbucket? I'm struggling to build one myself. Or can you point me to some instructions?

**Pull request merged**
