### PR TITLE
Support contextmenu ("right click") events using sendEvent('contextmenu')

### PR DESCRIPTION
**Pull request by Artur-**

### CODE REVIEW

**Comment by ariya** [comment]
Do we have an issue filed for this yet? If not, please do so. See the [contribution guidelines](https://github.com/ariya/phantomjs/blob/master/CONTRIBUTING.md) for the details.

**Comment by Artur-** [comment]
Update commit message with link to PhantomJS issue: https://github.com/ariya/phantomjs/issues/11429 and Ghostdriver issue: https://github.com/detro/ghostdriver/issues/125

**Comment by Vitallium** [comment]
LGTM

**Comment by Artur-** [comment]
Is the Ghostdriver project (https://github.com/detro/ghostdriver/) still used in PhantomJS or should I include the Ghostdriver patch for the local copy in this PR also?

**Comment by Vitallium** [comment]
@Artur- it's still used. But it's a bit outdated. We have included the streamline copy of Ghostdriver. All Ghostdriver related changes must be submitted against the original repo.
So please open appropriate pull request in the Ghostdriver repository.

**Comment by Artur-** [comment]
Ok, https://github.com/detro/ghostdriver/pull/472 is already there waiting for approval

**Comment by Vitallium** [comment]
@Artur- Thanks! I'll merge current pull request in a few minutes.

**Comment by Vitallium** [comment]
Sorry for taking it so long. Landed in master (https://github.com/ariya/phantomjs/commit/20d673bf208d9f3bbafa7f5e577a3b16705292a5) Thank you!

**Pull request closed without merging**
