### PR TITLE
Add an optional quality parameter to renderBase64

### PR DESCRIPTION
**Pull request by ghost**
The render function which saves a screenshot to disk takes a quality parameter but renderBase64 doesn't.
This change adds an optional quality parameter to the renderBase64 function so that quality of the image can be controlled.

https://github.com/ariya/phantomjs/issues/12474

### CODE REVIEW

**Comment by paulborza** [comment]
By the way, I've added tests too. Please take a look at this super simple PR and merge to master if it looks good. Thanks!

**Comment by Vitallium** [comment]
LGTM

**Comment by ghisguth** [comment]
LGTM, can this PR be merged?

**Comment by paulborza** [comment]
@Vitallium is there anything else needed from me in order to merge this PR? Thanks!

**Pull request merged**
