### PR TITLE
Change git:// to https://

### PR DESCRIPTION
**Pull request by SamanShafigh**

### CODE REVIEW

**Comment by Vitallium** [comment]
Why should we change these?

**Comment by zackw** [comment]
Since the project doesn't use signed commits, I believe cloning over `https://` instead of `git://` *does* provide an additional increment of integrity protection, but I don't know if that's what @SamanShafigh had in mind.

**Comment by Vitallium** [comment]
@SamanShafigh could you please update your PR?

**Comment by GunsAkimbo** [comment]
tip: `git config --global url."https://".insteadOf git://`

**Comment by zackw** [comment]
I'm going to close this since there has been no response from the original submitter as to why they wanted to make the change.

**Pull request closed without merging**
