### PR TITLE
Move documentation from gh-pages to master branch under /docs

### PR DESCRIPTION
**Pull request by saibotsivad**
_Note: This discussion was started in the Google Group, and this pull request was opened as part of that discussion._
# Motivation

The documentation and code for PhantomJS exist in different branches. When a pull request is made for a code change, the modification to the documentation is necessarily in a separate pull request. This leads to situations where a pull request for documentation is merged before the pull request for code changes is merged. As an example, see:
- Unmerged Code: https://github.com/ariya/phantomjs/pull/13345
- Documentation (merged 2015-12-22): https://github.com/ariya/phantomjs/pull/13824

(No blame or finger pointing is intended, just using it as an example.)
# Proposal

I propose that the documentation be moved from the `gh-pages` branch, and kept as a sub-directory under the `master` branch, and I am willing to do the work to make the transition.

Also note that Github extremely recently (2016-08-17) added functionality for Github Pages (JekyllRB) to be published from the master branch, if the documentation is placed in a sub-folder titled "doc". This means the site can still be published using Github Pages.
# Changes Made

It was my attempt (and I believe I have achieved it) to have the URL structure maintained between the old and new documentation. For example, the [webpage `event` URL](http://phantomjs.org/api/webpage/property/event.html) is the same before and after this pull request.
- Copied all files from gh-pages and put them in a subfolder names `docs`.
- Updated the Github URL in the _config.yml so the banner links to the new location.
- Update to use built-in Jekyll SASS compilation by moving scss files to _sass.
- Transition the API documentation to be a Jekyll collection, so that organization is easier.
- Move remaining content from _posts so that they are generated as static pages, thus eliminating the need for date prefixes in file names.
- Some minor gitignore tweaks.
# Operational Details

After this pull request is merged, the settings for this repository will need to be updated, so that the correct branch/folder is used for Github Pages. _(See [this Github blog post](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/) for more details.)_ This would need to be updated to point to the master branch, under the `/docs` folder. No other Github settings should be necessary.
# Additional Notes

If this gets merged, that will mean the documentation is _more likely_ to be in parity with the code, but of course will not guarantee that it is.

Therefore, after the merge I will be doing a bit of a deep-dive research to update the docs to actually be in parity with the code. I'll probably propose some formatting syntax to say "this is available in version X but not Y", since it seems we should be maintaining documentation for `1.x` and `2.x`.

### CODE REVIEW

**Comment by brutalcrozt** [comment]
Is this already done, i also make PR that do update on example. Which still open at this time.
I want to mention if add the documentation on [devdoc](devdocs.io) is a good idea.
Currently phantomjs is have 113 vote on their [thrello board](https://trello.com/c/gOLIq2Wl/178-phantomjs)

I am willing to do the work with a little guidance :smile: , sorry i am still a student

**Review by haroon-sheikh — APPROVED** [review]
The changes look good in terms of the post https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by haroon-sheikh** [comment]
We should look at all the open PR's before merging this in, to save us from conflicts etc.

**Comment by saibotsivad** [comment]
Coming up on a year now, and the existing docs are still as broken and incorrect as ever. :tada:

Merging this pull request does not mean that the existing docs will be correct, it only means that the existing docs _can be made correct_. The only way that is possible with the current documentation approach is to wait merge two pull requests simultaneously (one for the code, one for the docs).

Who has the keys or the authority to make this change?

**Comment by saibotsivad** [comment]
PhantomJS is [abandonware](https://en.wikipedia.org/wiki/Abandonware). Hopefully someone with time and/or finances can get involved and make this project usable again.

I'm closing this PR because I'm frustrated getting notifications from GitHub about an abandoned project. Sorry @ariya and company, I wish you the best.

**Pull request closed without merging**
