### PR TITLE
Selectively capture the response body

### PR DESCRIPTION
**Pull request by peter23**
It's about issue https://github.com/ariya/phantomjs/issues/10158

### CODE REVIEW

**Comment by jibay** [comment]
+1 this could be very cool to implement this feature

**Comment by LinusU** [comment]
This would be very good to have, currently impossible to download attachments :(

**Comment by Vitallium** [comment]
This feature has been landed to `master` actually. See https://github.com/ariya/phantomjs/blob/master/src/webpage.h#L206

**Comment by LinusU** [comment]
@Vitallium cool! Not sure that passing it as a string is such a good idea thought #13338

**Pull request closed without merging**
