### PR TITLE
Include Web Inspector resources.

### LINKED ISSUE #12864: PhantomJS 2 remote debugging is broken
After running phantomjs with _--remote-debugger-port=8080_ and trying to debug with Google Chrome (Version 39.0.2171.95) "about:blank" link is missing. Also I tried to forcefully go to http://127.0.0.1:8080/webkit/inspector/inspector.html?page=1 but that produces empty page with no debugging capabilities.
Tested on Windows 7 with PhantomJS 2.0 built from source.

### PR DESCRIPTION
**Pull request by vitallium**
Include Web Inspector resources.

Fixes #12864

### CODE REVIEW

**Comment by ariya** [comment]
Landed. Thanks!

**Comment by ariya** [comment]
It causes the following error on OS X:

```
duplicate symbol __Z21qInitResources_WebKitv in:
    qrc_WebKit.o
    /Users/ariya/dev/ariya/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_WebKit.o)
duplicate symbol __Z24qCleanupResources_WebKitv in:
    qrc_WebKit.o
    /Users/ariya/dev/ariya/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_WebKit.o)
duplicate symbol __Z39qInitResources_InspectorBackendCommandsv in:
    qrc_InspectorBackendCommands.o
    /Users/ariya/dev/ariya/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_InspectorBackendCommands.o)
duplicate symbol __Z42qCleanupResources_InspectorBackendCommandsv in:
    qrc_InspectorBackendCommands.o
    /Users/ariya/dev/ariya/phantomjs/src/qt/qtwebkit/Source/WebCore/release/libWebCore.a(qrc_InspectorBackendCommands.o)
ld: 4 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Vitallium** [comment]
I'll check it.

**Comment by Vitallium** [comment]
Fixed. Will update this PR soon.

**Comment by ariya** [comment]
@Vitallium It's not clear to me which part fixes it since I landed your earlier commit. Could you double check if the current 2.0 looks good?

**Comment by Vitallium** [comment]
This one is fixes Webkit Resources. Linux (and OS X) build already has resources. But on Windows we should include them directly.

**Comment by ariya** [comment]
@Vitallium Sounds good, I'll close this one and please open a new PR if there are still changes needed. Thanks!

**Pull request closed without merging**
