### PR TITLE
Support for SSL Client Authentication #11275

### PR DESCRIPTION
**Pull request by ffray**
Hi there,

I've just been asked to create a pull request for this feature.
Please have a look and pull this change.

Best regards,

Florian

### CODE REVIEW

**Comment by jefleponot** [comment]
Hi FFray,

Could you precise how to use your feature ?
-format file PEM / PF12 ...
-errors
- etc

Thanks in advance

**Comment by JamesMGreene** [comment]
@Vitallium @ariya Can either of you take a look at this PR?  It's been peculiarly unreviewed for over a year. :confused:

**Comment by Vitallium** [comment]
@JamesMGreene sure. No problem. I'll take a look.

**Comment by Vitallium** [comment]
LGTM, but requires one small tweak - close the key file after it was loaded. Anyway I'll merge it.

/cc @ariya @ffray

**Comment by Vitallium** [comment]
Thank you! Landed in 37a3c2d!

**Pull request closed without merging**
