### PR TITLE
proxy exceptions

### PR DESCRIPTION
**Pull request by jefleponot**
#12131

add a new command line option : --no-proxy
to filter proxy exceptions

it compiles and works well to me :-)

Can you help me to complete tests files ?
Cu everybody

### CODE REVIEW

**Comment by gaje** [comment]
Do you have a stable build that includes the --no-proxy proxy exceptions that you can send me? I compiled the source code from your fork, which compiled successfully, but upon running phantom crashes immediately.

**Comment by jefleponot** [comment]
Hi gaje,

I used my phantom fork on ubuntu 14.04 x86_64 and Centos 5.6 x86_64 to supervise web sites.
No crashed occurs.

Regards

**Comment by zackw** [comment]
We apologize for ignoring this PR for nearly a year.

I don't understand what you mean by "add a new command line option --no-proxy to filter proxy exceptions", and the code doesn't clarify matters enough for me to be sure.  Could you please try again to explain the new feature?

**Comment by gabel** [comment]
@zackw Any chances this will be resolved? Is a new PR needed?

**Comment by kramsee** [comment]
@zackw Have you seen the issue #12131? The discussion over there clarified this pull request for me.

**Comment by Vitallium** [comment]
We already have `WebPage::setProxy` method. I suggest to change it a bit to accept an empty string that clears the proxy for the web page.

**Comment by gabel** [comment]
I need it for a `behat > selenium > phantomjs` workflow and this for in the `phantomjs cli`.

**Comment by gabel** [comment]
@zackw Any news to accept this? Any infos needed? Should this PR be refactored?

**Comment by jefleponot** [comment]
Hi @gabel , @Vitallium , @kramsee , @zackw , @gaje 

This feature was important for me with phantom 1.9.7 because many of web Intranet appliances (direct access) required Internet Data geolocation (proxies configuration)

So I need the same features that a real web browser (graphic browser that means) , more than WebPage::setProxy . Can you filter each url in using setProxy on request event (very user-friendly) ?

capture du 2016-03-17 09 03 45

Fortunately, phantomJS 2.1.1 use  environment variables on Linux so I didn't have to use my PR any more with this workaround just using : 
- http_proxy=...
- https_proxy=...
- no_proxy=...

I don't know about windows environment variables.

Best Regards
jef

**Comment by gabel** [comment]
@jefleponot thx for the information, i'm going to check the environment `no_proxy` option with phantomJS 2.1.1 -- lets pray it works...

**Comment by EugenioLaghi** [comment]
Any news on this feature?

**Comment by gabel** [comment]
@EugenioLaghi After switching to phantomJS >= 2.1.1 the environmental `no_proxy` works finally. So from my point of view this feature is not required anymore.

**Comment by petestorey26** [comment]
The environment variable doesn't do anything if you're just using PhantomJS directly - perhaps if you have some complex selenium setup it does, but if I search the source of master for PhantomJS, there is no reference to no_proxy at all :(

This feature would be very useful - to be able to not use a proxy for specific hosts, because you want to handle them separately.

**Comment by gabel** [comment]
@petestorey26 I guess it's not phantomJS but a dependency. We're able to use `no_proxy` since 2.1.x

**Comment by petestorey26** [comment]
OK thanks, so what are you using then?  Are you having something else drive phantom and provide the proxying?

**Pull request closed without merging**
