### PR TITLE
add a resourceTimeout parameter to phantomjs from 2.1.1

### PR DESCRIPTION
**Pull request by jefleponot**
#14911

No event never trigger on popup opening. Because you can't precise a page.resourceTimeout before a "window.open event" that create the new popup.

And This timeout equals 0 by default. So It could be nice if we can fix it before running execution.
It will avoid crashs on no response services.

Regards

### CODE REVIEW

**Comment by jefleponot** [comment]
@Vitallium / @ariya 
Could you please integrate this fix bug ?

**Comment by jefleponot** [comment]
Is the 2.1.1 version is a Long Term Sable Executable ?

**Comment by Vitallium** [comment]
@jefleponot Nop. We almost ready to release 2.5 version. With 2.5 release we will deprecate 2.1.

**Comment by jefleponot** [comment]
@Vitallium 
It seams that the next release will have the same bug...

**Pull request merged**
