### PR TITLE
Provides ability to compile PhantomJS with new webkit code

### PR DESCRIPTION
**Pull request by matteoceraico**
I tested my work on MacOSX El Capitan and everything works properly (you need to install cmake through brew). In these days i will try to compile PhantomJS on a linux system but please consider that i’m not able to do the same thing on a windows system, i think Vitallium is working on this. 

My qtwebkit-phantom branch has the following differences:
- https://github.com/matteoceraico/webkit/commit/c96d163b03cd100b14dbefd77291a1a5f2c245ab (Supported multiple console.log arguments) - this patch is similar to https://github.com/ariya/phantomjs/commit/ac699a4d90
- https://github.com/matteoceraico/webkit/commit/dac9f105edf265910ea327a47e57ba85c2a1b9af (Provided ability to set qt compile definitions to use) - by passing CXX_FLAGS to build-webkit script, webkit is compiled properly but the libraries generate linker errors during the build of phantom, because of this i've implemented this feature

I forked qtbase (branch 5.6.1, this version is needed in order to be able to use c++11 compiler on mac systems) because we need to import phantom plugin, by talking with Vitallium it seems that we should be able to use a builtin plugin so the fork will be not needed anymore.

build.py is working as usual, i’ve also added the ability to disable touch events by using the option --disable-touch-events

Let me know

### CODE REVIEW

**Comment by Vitallium** [comment]
YAY! I also have a few changes (Windows specific) for your pull request in annulen/webkit I'll post them later :)

**Comment by Vitallium** [comment]
I don't think we need to pull submodules back. The idea was actually in removing them completely from our source tree.

/cc @ariya

**Comment by Vitallium** [comment]
I think I should write the complete vision of the upcoming release 2.5.

Let's go back in time. We have in our source tree the full source packages for Qt and QtWebKit. Why? Because we need to patch them to support necessary features and to be able to build PhantomJS statically. But keeping two packages became a huge problem: we've been receiving bug reports for all submodules: PhantomJS itself, Qt and QtWebKit. We are a tiny team of developer who works on this project in their spare time. We physically don't have time to support all packages. That's why we have the enormous amount of issue right now. We definitely should do something.

And we are doing!

Splitting (removing) Qt and QtWebKit brings a fresh air to the project. Because we can forward non-PhantomJS issues to upstream bug trackers. Qt bugs go to Qt bug tracker, QtWebKit to QtWebkit and so on. We want to keep our issue tracker with PhantomJS issues only. Applying that change will help us to focus on developing PhantomJS and fixing its problems.

Cheers!

**Comment by matteoceraico** [comment]
Personally, i like the current approach because in this way we're able to implement specific code for PhantomJS in the webkit code. For example the "stupid" patch for the console logs (https://github.com/matteoceraico/webkit/commit/c96d163b03cd100b14dbefd77291a1a5f2c245ab) is needed in PhantomJS but it is not needed in webkit code. Moreover in the current way we're able to compile webkit with/without the touch events enabled by default.

Another good point is the fact that we don't need to install qt in the system and a binary with few dependencies is generated.

Anyway, I'm really in accordance with you about the fact that in this way you will be able to focus on the development of PhantomJS, i feel you about the time problem!

**Comment by Vitallium** [comment]
@matteoceraico in order to build PhantomJS statically the user must have Qt and QtWebKit on the same machine. I think we can keep special patches on our repo that the developer must apply to QtWebKit.

**Comment by ariya** [comment]
@matteoceraico Each approach has its pros and cons. The approach of including the copies of Qt/QtWebKit was necessary back then when QtWebKit development stalled. It's not the case anymore. Beside, it should be a stop-gap measure anyway. Doing so in the long run is not sustainable for the development/maintenance teams, no matter how attractive it is.

If what you want to achieve if custom building PhantomJS, that is not code dependencies issue, that is packaging issue. I recommend that you follow/track/help us with #14459 instead.

**Comment by Vitallium** [comment]
Closing this. Not relevant anymore.

**Pull request closed without merging**
